# Generated by Django 3.2 on 2021-04-12 15:47

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, upload_to=courses.models.save_class_image, verbose_name='class image'),
        ),
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=550, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Lecture No')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=courses.models.save_lecture_files, verbose_name='video')),
                ('ppt', models.FileField(blank=True, upload_to=courses.models.save_lecture_files, verbose_name='ppt')),
                ('notes', models.FileField(blank=True, upload_to=courses.models.save_lecture_files, verbose_name='notes')),
                ('class_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tutor')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
