# Generated by Django 3.2 on 2021-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210412_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
