# Generated by Django 3.2 on 2021-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reviewandcomment'),
        ('courses', '0006_auto_20210429_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='home.Student'),
        ),
    ]
