# Generated by Django 3.2 on 2021-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_reviewandcomment_subject'),
        ('courses', '0010_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='home.Student'),
        ),
    ]
