# Generated by Django 3.1.7 on 2021-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_ad_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_student',
            name='usr_type',
            field=models.CharField(default='st', max_length=10),
        ),
        migrations.AddField(
            model_name='ad_tutor',
            name='usr_type',
            field=models.CharField(default='tt', max_length=10),
        ),
    ]
