# Generated by Django 3.1.7 on 2021-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20210428_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_student',
            name='salary',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_tutor',
            name='expected_salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
