# Generated by Django 3.1.7 on 2021-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_student_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_student',
            name='salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ad_tutor',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
